#!/usr/bin/env bash

set -e

# Check for required tools
for cmd in git bash; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: Required tool '$cmd' is not installed. Please install it and try again."
    exit 1
  fi
done

# Check for Dotbot
if [ ! -x "dotbot/bin/dotbot" ]; then
  git submodule update --init --recursive
fi

# Usage/help message
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "Usage: ./install [dotbot options]"
  echo "This script auto-detects your profile and runs Dotbot with the appropriate config."
  exit 0
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# Install configuration for all profiles
for PROFILE_DIR in profiles/*; do
  PROFILE="$(basename "${PROFILE_DIR}")"
  DETECT_CMD="${PROFILE_DIR}/detect"

  if [[  ! -f "${DETECT_CMD}" ]]; then
    echo "No ${DETECT_CMD} file for profile ${PROFILE}; skipping"
    continue
  fi

  if "${DETECT_CMD}"; then
    printf "\033[0;32m==> 🟢 Profile ${PROFILE} detected: running dotbot\033[0m\n"
     "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PROFILE_DIR}/install.conf.yaml" "$@"
    printf "\033[0;32m==> ✅ Profile ${PROFILE} configured.\n"

  else
    printf "\033[0;32m==> 🟡 Profile ${PROFILE} not detected: skipping dotbot\033[0m\n"
  fi
  echo
done
